name: api-build

on:
  push:
    paths:
      - ".github/workflows/api-build.yml"  
      - 'api/**'
  workflow_dispatch: # manual

jobs:
  build:
    name: build-dotnet-api
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - run: dotnet --list-runtimes
      - run: dotnet --list-sdks
      - run: dotnet build -c Release 
        working-directory: ./api
      - run:  dotnet test --logger "trx;LogFileName=test_results.trx" --results-directory TestResults
        working-directory: ./tests/api.Tests
      - uses: actions/upload-artifact@v4
        with:
          name: "api-build-artifact-${{ matrix.os }}"
          path: |
            ./api/bin/Release/net8.0
            ./tests/api.Tests/TestResults