name: api-image

on:
  push:
    paths:
      - ".github/workflows/api-image.yml"  
      - 'api/**'
  workflow_dispatch: # manual

permissions:
  packages: write

jobs:
  image:
    name: build-dotnet-api-image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker version
      - run: docker image build -t dotnet-api-image .
        working-directory: ./api