name: butler

on:
  issue_comment: 
    types: created
  workflow_dispatch: # manual

permissions:
  pull-requests: write

jobs:
  chat:
    runs-on: ubuntu-latest
    steps:
        - run: echo 'Received comment ${{ github.event.comment.body }}'