name: upper-build

on:
  push:
    paths:
      - ".github/workflows/upper-build.yml"
      - 'upper/**'
  workflow_dispatch: # manual

jobs:
  build:
    name: python-build
    runs-on: ubuntu-latest
    steps:
      - run: pwd && ls - al
      - uses: actions/checkout@v4
      - run: pwd && ls - al
      - run: python --version
      - uses: actions/setup-python@v4
        with:
          python-version: '3.13.5'
      - run: python --version